# Cloud Build pipeline that tidies modules, builds binaries, and deploys to Cloud Run.
substitutions:
  _SERVICE: pdf2jpg
  _REGION: us-central1
  _REPOSITORY: us-central1-docker.pkg.dev/$PROJECT_ID/pdf2jpg/pdf2jpg

steps:
  - name: golang:1.22-bookworm
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        mkdir -p /workspace/bin
        go mod tidy
        go build ./...
        GOBIN=/workspace/bin go install ./cmd
        if [ -f /workspace/bin/cmd ]; then mv /workspace/bin/cmd /workspace/bin/main; fi

  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - '--file=Dockerfile'
      - '--tag=${_REPOSITORY}:${COMMIT_SHA}'
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_REPOSITORY}:${COMMIT_SHA}'

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        gcloud run deploy ${_SERVICE} \
          --project ${PROJECT_ID} \
          --region ${_REGION} \
          --image ${_REPOSITORY}:${COMMIT_SHA} \
          --allow-unauthenticated \
          --set-env-vars PORT=8080 \
          --set-secrets API_KEYS=projects/${PROJECT_ID}/secrets/pdf2jpg-api-key:latest

images:
  - '${_REPOSITORY}:${COMMIT_SHA}'
